name: Deploy to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print GitHub Context
        run: |
          echo "Repository=${{ github.repository }}"
          echo "Ref=${{ github.ref }}"
          echo "Workflow=${{ github.workflow }}"

      - name: Debug OIDC Token
        uses: github/actions-oidc-debugger@main
